### ISSUE TITLE
Sideways movement

### ISSUE THREAD

**Issue by angelickite** [tsoding/raycasting#21]
As an alternative to always rotating, a sideways movement _might_ make sense, depending on where this game is going.

**Comment by angelickite** [comment]
I have implemented this feature to get familiar with the project. If desired I can open a pull request.

**Comment by rexim** [comment]
Yeah, I wanted to implement classical FPS controls, with left/right/A/D being sideways movement, and rotating with mouse (horizontally, our engine does not allow looking up or down). But that requires locking/unlocking the mouse somehow and I haven't learnt how to do that in Web yet. If you also implement that feel free to submit a PR, sure.

**Comment by rexim** [comment]
Is there any stable pointer locking API or everything is either deprecated or not widely available?

**Comment by rexim** [comment]
Whatever, I'll research and implement this myself.

**Comment by angelickite** [comment]
I am not a web native myself and will definitely continue staying from web as far away as possible. Wish you good luck.
