### ISSUE TITLE
Canvas buffer vs. display dimensions

### ISSUE THREAD

**Issue by angelickite** [tsoding/raycasting#24]
The buffer of the canvas is based on a multiple of the 16:9 aspect ratio. Also, when resizing the browser window, the canvas uses 100% of the available height. That combination leads to a mismatch between canvas buffer dim and the canvas display dim. When the canvas buffer then gets drawn by the browser, it gets upscaled with some sort of interpolation leading to a blurry image. (see `canvas.width/height` vs. `canvas.style.width/height`)

Currently there is already some code in place to counteract the smoothing when drawing onto the canvas: `ctx.imageSmoothingEnabled = false;`. However, this doesn't prevent the smoothing during the canvas upscaling from buffer to display.

A simple fix would be to add the following style to the canvas: `image-rendering: pixelated;`

Having both these settings in place leads to the (I assume...) desired presentation.

**Comment by rexim** [comment]
I know about this, and how to fix it. The final look and feel is a work and progress.
