### ISSUE TITLE
Hint

### ISSUE THREAD

**Issue by cheblin** [tsoding/raycasting#30]
A `Vector3` object with three number fields (`x`, `y`, `z`) in JavaScript can be analyzed in terms of its memory usage as follows:

### Memory Usage Breakdown for Vector3 Object

1. **Base Object Overhead**:
   - The base overhead for an empty object in JavaScript is approximately 24 bytes.

2. **Number Field Storage**:
   - Each number field typically takes up 8 bytes (assuming a double-precision 64-bit floating point representation as per the IEEE 754 standard).
   - With 3 number fields (`x`, `y`, `z`), this amounts to 24 bytes for the field values.

3. **Property Overhead**:
   - Each property in a JavaScript object includes a key and a pointer to the value.
   - The overhead for each property key and pointer is approximately 8 to 12 bytes.
   - For 3 properties, the overhead can range from 24 to 36 bytes.

### Estimated Total Memory Usage

1. **Base Object**: 24 bytes
2. **Number Fields**: 24 bytes
3. **Property Overhead**: 24 to 36 bytes

**Estimated Total**: 24 + 24 + 24 to 36 = **72 to 84 bytes**

### Summary

A `Vector3` object with three number fields (`x`, `y`, `z`) in JavaScript can consume approximately 72 to 84 bytes of memory. This includes the base object overhead, storage for the number values, and the overhead for the property keys and pointers.

### Memory Usage Calculation in JavaScript

Here is an example of how a `Vector3` object might be defined in JavaScript:

```javascript
class Vector3 {
    constructor(x, y, z) {
        this.x = x;
        this.y = y;
        this.z = z;
    }
}

let vec = new Vector3(1.0, 2.0, 3.0);
```

### Conclusion

The `Vector3` object is relatively memory-efficient, given the typical use cases involving numerical computations. While there is some overhead due to the property management in JavaScript objects, the total memory usage remains manageable for most applications.

If you are really interested in optimizing for high performance and memory efficiency, using separate arrays for each field (`x`, `y`, `z`) can be more efficient than using an array of `Vector3` objects. This approach is known as the **Structure of Arrays (SoA)** pattern, which contrasts with the **Array of Structures (AoS)** pattern. 

#### Array of Structures (AoS)

```javascript
class Vector3 {
    constructor(x, y, z) {
        this.x = x;
        this.y = y;
        this.z = z;
    }
}

let vectors = [
    new Vector3(1.0, 2.0, 3.0),
    new Vector3(4.0, 5.0, 6.0),
    new Vector3(7.0, 8.0, 9.0)
];
```

In this pattern, you have an array of objects, each containing all the fields. While this is easy to understand and work with, it can be less efficient in terms of memory usage and performance due to object overhead and non-contiguous memory access patterns.

#### Structure of Arrays (SoA)

```javascript
let x = new Float64Array([1.0, 4.0, 7.0]);
let y = new Float64Array([2.0, 5.0, 8.0]);
let z = new Float64Array([3.0, 6.0, 9.0]);
```

In this pattern, each field has its own contiguous array. This approach is more memory efficient and can lead to better performance, especially in computationally intensive applications, due to improved cache locality and reduced object overhead.

### Advantages of Structure of Arrays (SoA)

1. **Memory Efficiency**: Avoids the per-object overhead associated with JavaScript objects.
2. **Cache Locality**: Contiguous memory layout improves CPU cache efficiency, leading to better performance.
3. **Vectorized Operations**: More amenable to SIMD (Single Instruction, Multiple Data) operations, which can be leveraged by modern JavaScript engines and hardware.
4. **Reduced Garbage Collection Overhead**: Fewer objects mean less work for the garbage collector.

#### AoS Example

```javascript
function computeMagnitudesAoS(vectors) {
    return vectors.map(v => Math.sqrt(v.x * v.x + v.y * v.y + v.z * v.z));
}

let vectors = [
    new Vector3(1.0, 2.0, 3.0),
    new Vector3(4.0, 5.0, 6.0),
    new Vector3(7.0, 8.0, 9.0)
];

let magnitudes = computeMagnitudesAoS(vectors);
```

#### SoA Example

```javascript
function computeMagnitudesSoA(x, y, z) {
    let magnitudes = new Float64Array(x.length);
    for (let i = 0; i < x.length; i++) {
        magnitudes[i] = Math.sqrt(x[i] * x[i] + y[i] * y[i] + z[i] * z[i]);
    }
    return magnitudes;
}

let x = new Float64Array([1.0, 4.0, 7.0]);
let y = new Float64Array([2.0, 5.0, 8.0]);
let z = new Float64Array([3.0, 6.0, 9.0]);

let magnitudes = computeMagnitudesSoA(x, y, z);
```

### Conclusion

Using the Structure of Arrays (SoA) pattern can lead to significant performance improvements in applications where large arrays of numerical data are processed. It offers better memory efficiency and computational performance due to improved cache locality and reduced overhead. However, the choice between AoS and SoA should be based on the specific requirements and constraints of your application.

Using the Structure of Arrays (SoA) pattern also reduces the pressure on the garbage collector (GC). Here’s why:

### Lower Garbage Collection Pressure with SoA

1. **Fewer Objects**: In the SoA pattern, you are dealing with fewer objects since each array is a single object. In contrast, the Array of Structures (AoS) pattern creates many individual objects, increasing the number of items the GC needs to track and collect.
  
2. **Contiguous Memory Allocation**: Arrays in SoA are contiguous in memory, which can be more efficient for the GC to handle. This contrasts with the scattered memory allocation of many small objects in AoS, which can lead to memory fragmentation and increased GC workload.

3. **Simpler Allocation and Deallocation**: Allocating and deallocating large contiguous blocks of memory (like arrays) is generally more efficient than handling many small, scattered objects. This can result in faster GC cycles.

#### Array of Structures (AoS)

```javascript
class Vector3 {
    constructor(x, y, z) {
        this.x = x;
        this.y = y;
        this.z = z;
    }
}

let vectors = [];
for (let i = 0; i < 1000000; i++) {
    vectors.push(new Vector3(Math.random(), Math.random(), Math.random()));
}
```

#### Structure of Arrays (SoA)

```javascript
let x = new Float64Array(1000000);
let y = new Float64Array(1000000);
let z = new Float64Array(1000000);

for (let i = 0; i < 1000000; i++) {
    x[i] = Math.random();
    y[i] = Math.random();
    z[i] = Math.random();
}
```

### Impact on Garbage Collection

1. **Initialization**: In AoS, each `Vector3` object needs to be created individually, putting immediate pressure on the GC to manage these objects. In SoA, only three large arrays are created, reducing the initial GC overhead.

2. **Lifetime Management**: With AoS, the GC must track the lifecycle of each `Vector3` instance. If these objects are short-lived, it increases the frequency of GC cycles. In SoA, the arrays are typically long-lived and only require the GC to manage three objects.

3. **Memory Fragmentation**: AoS can lead to memory fragmentation due to the allocation of many small objects. This fragmentation can degrade GC performance over time. SoA minimizes fragmentation by allocating large contiguous blocks of memory.

### Conclusion

Using the Structure of Arrays (SoA) pattern not only improves memory efficiency and computational performance but also reduces the pressure on the garbage collector. This is especially beneficial in applications with large datasets or real-time processing requirements, where minimizing GC pauses is crucial for maintaining performance.

**Comment by rexim** [comment]
Consider submitting a PR that utilizes these ideas and demonstrates that they actually improve the game.
